export const tagApi = [
  { key: 1, title: "C" },
  { key: 2, title: "C++" },
  { key: 3, title: "Java" },
  { key: 4, title: "Html" },
  { key: 5, title: "Css" },
  { key: 6, title: "Js" },
  { key: 7, title: "Ts" },
  { key: 8, title: "博客" },
  { key: 9, title: "logo" },
  { key: 10, title: "3d" },
  { key: 12, title: "web" },
  { key: 13, title: "ui" },
  { key: 14, title: "技术" },
  { key: 15, title: "其它项目" },
  { key: 16, title: "前端" },
  { key: 17, title: "后端" },
  { key: 18, title: "嵌入式" },
  { key: 19, title: "电路" },
  { key: 20, title: "腾讯云" },
  { key: 21, title: "GitHub" },
  { key: 22, title: "HTTP" },
  { key: 23, title: "浏览器" },
  { key: 24, title: "NodeJS" },
  { key: 25, title: "Flex" },
  { key: 26, title: "LeetCode" },
];
